### ISSUE TITLE
dimension mismatch 

### ISSUE THREAD

**Issue by pykao** [kexinhuang12345/MolTrans#20]
Dear Kexin,

Great work!

When I tried to run the training code: `CUDA_VISIBLE_DEVICES=0,2,3,4,5,7 python train.py --task biosnap`, it gave me the following error:

```
Let's use 6 GPUs!
--- Data Preparation ---
Traceback (most recent call last):
  File "train.py", line 207, in <module>
    model_max, loss_history = main()
  File "train.py", line 157, in main
    auc, auprc, f1, logits, loss = test(testing_generator, model_max)
  File "train.py", line 64, in test
    loss = loss_fct(logits, label)
  File "/home/ken/anaconda3/envs/MolTrans/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ken/anaconda3/envs/MolTrans/lib/python3.7/site-packages/torch/nn/modules/loss.py", line 612, in forward
    return F.binary_cross_entropy(input, target, weight=self.weight, reduction=self.reduction)
  File "/home/ken/anaconda3/envs/MolTrans/lib/python3.7/site-packages/torch/nn/functional.py", line 3058, in binary_cross_entropy
    "Please ensure they have the same size.".format(target.size(), input.size())
ValueError: Using a target size (torch.Size([16])) that is different to the input size (torch.Size([12])) is deprecated. Please ensure they have the same size.
```
I think there is a dimension mismatch when we calculate the loss `loss=loss_fct(logits, label)`

Could you please help on solving this issue?

Best,
Po-Yu

**Comment by pykao** [comment]
It works when using only four GPUs `CUDA_VISIBLE_DEVICES=2,3,4,5 python train.py --task biosnap`.

I think there is a bug.
